pipeline {
    agent any

    environment {
        PROPERTIES_FILE = 'pipeline.properties'
    }

    stages {
        stage('Load Properties') {
            steps {
                script {
                    def props = readProperties file: PROPERTIES_FILE
                    env.GIT_REPO_URL = props.GIT_REPO_URL
                }
            }
        }
        stage('Checkout') {
            steps {
                git "${env.GIT_REPO_URL}"
            }
        }
        stage('Build') {
            steps {
                dir('api-test-automation') {
                    sh './gradlew clean build'
                }
            }
        }
        stage('Test') {
            steps {
                dir('api-test-automation') {
                    sh './gradlew test'
                }
            }
        }
    }

    post {
        always {
            dir('api-test-automation') {
                archiveArtifacts artifacts: '**/build/reports/**/*.html', allowEmptyArchive: true
                junit 'build/test-results/test/*.xml'
            }
        }
    }
}
