pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://your-repo-url.git'
            }
        }
        stage('Build') {
            steps {
                dir('ui-test-automation') {
                    sh './gradlew clean build'
                }
            }
        }
        stage('Test') {
            steps {
                dir('ui-test-automation') {
                    sh './gradlew test'
                }
            }
        }
    }

    post {
        always {
            dir('ui-test-automation') {
                archiveArtifacts artifacts: '**/build/reports/**/*.html', allowEmptyArchive: true
                junit 'build/test-results/test/*.xml'
            }
        }
    }
}
